# -*- coding: utf-8 -*-
"""原站 98 道题的原页面清单（附录 B 用）。由笔记文件自动提取，勿手改。"""

QUESTIONS = [
    ("Agent", 1, "什么是 Agent？与大模型有什么本质不同？", "https://xiaolinnote.com/ai/agent/1_whatisagent.html"),
    ("Agent", 2, "Agent 的基本架构由哪些核心组件构成？", "https://xiaolinnote.com/ai/agent/2_components.html"),
    ("Agent", 3, "Workflow，Agent，Tools 这三个的概念和区别介绍一下？", "https://xiaolinnote.com/ai/agent/3_workflow_tools.html"),
    ("Agent", 4, "了解哪些其他的 Agent 设计范式？Agent 和 Workflow 的区别是什么？", "https://xiaolinnote.com/ai/agent/4_patterns.html"),
    ("Agent", 5, "Agent 推理模式有哪些？ReAct 是啥？具体是怎么实现的？", "https://xiaolinnote.com/ai/agent/5_react.html"),
    ("Agent", 6, "ReAct、Plan-and-Execute、Reflection 三种范式有什么核心区别？实际项目中该如何选型？", "https://xiaolinnote.com/ai/agent/6_three_patterns.html"),
    ("Agent", 7, "复杂任务怎么做的任务拆分？为什么要拆分？效果如何提升？", "https://xiaolinnote.com/ai/agent/7_tasksplit.html"),
    ("Agent", 8, "请你介绍一下 AI Agent 的记忆机制，并说明在实际开发中应该如何设计记忆模块？", "https://xiaolinnote.com/ai/agent/8_memory.html"),
    ("Agent", 9, "Agent 的长短期记忆系统怎么做的？记忆是怎么存的？粒度是多少？怎么用的？", "https://xiaolinnote.com/ai/agent/9_memory_storage.html"),
    ("Agent", 10, "什么是 Multi-Agent？", "https://xiaolinnote.com/ai/agent/10_multiagent.html"),
    ("Agent", 11, "说说 Single-Agent 和 Multi-Agent 的设计方案？", "https://xiaolinnote.com/ai/agent/11_single_multi.html"),
    ("Agent", 12, "Agent 记忆压缩通常有哪些方法？", "https://xiaolinnote.com/ai/agent/12_memcompress.html"),
    ("Agent", 13, "在工程实践中，为什么有时候选择「手搓」Agent，而不是直接用成熟框架？", "https://xiaolinnote.com/ai/agent/13_handcode.html"),
    ("Agent", 14, "如何赋予 LLM 规划能力？", "https://xiaolinnote.com/ai/agent/14_planning.html"),
    ("Agent", 15, "讲讲 Agent 的反思机制？为什么要用反思？具体怎么实现？", "https://xiaolinnote.com/ai/agent/15_reflection.html"),
    ("Agent", 16, "如何设计多 Agent 的协作与动态切换机制？", "https://xiaolinnote.com/ai/agent/16_collab.html"),
    ("Agent", 17, "Agent 的上下文工程怎么设计？", "https://xiaolinnote.com/ai/agent/17_context_engineering.html"),
    ("Agent", 18, "Agent 的多轮对话状态如何管理？如何防止跑偏并支持中断恢复？", "https://xiaolinnote.com/ai/agent/18_session_state.html"),
    ("Agent", 19, "如何评估一个 Agent 的效果？评测集和指标怎么设计？", "https://xiaolinnote.com/ai/agent/19_evaluation.html"),
    ("Agent", 20, "Agent 为什么会出现路径震荡、重复调用和死循环？怎么检测和治理？", "https://xiaolinnote.com/ai/agent/20_loop_stability.html"),
    ("Agent", 21, "线上 Agent 延迟明显升高时，如何通过 Trace 定位和优化？", "https://xiaolinnote.com/ai/agent/21_agent_latency_trace.html"),
    ("Agent", 22, "Multi-Agent 系统如何处理子 Agent 超时、失联和并发修改冲突？", "https://xiaolinnote.com/ai/agent/22_multi_agent_resilience.html"),
    ("Agent", 23, "Agent 的「任务幻觉」是什么？如何避免没有执行工具却声称任务已经完成？", "https://xiaolinnote.com/ai/agent/23_task_hallucination.html"),
    ("Agent", 24, "大模型或 Agent 连接数据库时，如何防止越权、敏感数据泄漏和查询幻觉？", "https://xiaolinnote.com/ai/agent/24_database_security.html"),
    ("RAG", 1, "什么是 RAG？详细描述一个完整 RAG 系统的工作流程？", "https://xiaolinnote.com/ai/rag/1_whatisrag.html"),
    ("RAG", 2, "大模型的 RAG 主要用来解决什么问题？", "https://xiaolinnote.com/ai/rag/2_rag_problems.html"),
    ("RAG", 3, "相比直接微调 LLM，RAG 解决了什么问题？微调和 RAG 各自的优劣势是什么？", "https://xiaolinnote.com/ai/rag/3_rag_vs_finetune.html"),
    ("RAG", 4, "RAG 中的文档是怎么存的？粒度是多大？详细说说文档切割（Chunking）策略？", "https://xiaolinnote.com/ai/rag/4_chunking.html"),
    ("RAG", 5, "怎么规避语义被切割掉的问题？", "https://xiaolinnote.com/ai/rag/5_semantic_cuts.html"),
    ("RAG", 6, "在 RAG 中 Embedding 究竟是什么？如何选择和评估一个 Embedding 模型？", "https://xiaolinnote.com/ai/rag/6_embedding.html"),
    ("RAG", 7, "Embedding 有哪几种算法你了解过吗？", "https://xiaolinnote.com/ai/rag/7_embedding_algos.html"),
    ("RAG", 8, "什么是向量数据库？有没有做过向量数据库的对比选型？", "https://xiaolinnote.com/ai/rag/8_vectordb.html"),
    ("RAG", 9, "讲讲你用的向量数据库？数据量级是多大？性能如何？遇到过性能瓶颈吗？", "https://xiaolinnote.com/ai/rag/9_vectordb_practice.html"),
    ("RAG", 10, "你使用 RAG 给大模型一个输入，系统是怎样的工作流程？", "https://xiaolinnote.com/ai/rag/10_online_workflow.html"),
    ("RAG", 11, "请你介绍一下向量检索和关键词检索的区别？", "https://xiaolinnote.com/ai/rag/11_retrieval_types.html"),
    ("RAG", 12, "如何润色用户的 Query（Query Rewrite）？目的是什么？", "https://xiaolinnote.com/ai/rag/12_query_rewrite.html"),
    ("RAG", 13, "什么是多路召回？具体怎么做？", "https://xiaolinnote.com/ai/rag/13_multi_retrieval.html"),
    ("RAG", 14, "RAG 检索优化策略有哪些？", "https://xiaolinnote.com/ai/rag/14_retrieval_opt.html"),
    ("RAG", 15, "了解哪些更复杂的 RAG 范式？", "https://xiaolinnote.com/ai/rag/15_advanced_paradigms.html"),
    ("RAG", 16, "在什么场景下，你会选择使用图数据库来增强传统的向量检索？", "https://xiaolinnote.com/ai/rag/16_graph_db.html"),
    ("RAG", 17, "如何规避 RAG 系统中大模型的幻觉？", "https://xiaolinnote.com/ai/rag/17_hallucination.html"),
    ("RAG", 18, "怎么量化你的 RAG 效果？", "https://xiaolinnote.com/ai/rag/18_evaluation.html"),
    ("RAG", 19, "RAG 知识库如何实现动态与持续更新？", "https://xiaolinnote.com/ai/rag/19_dynamic_update.html"),
    ("RAG", 20, "在实际落地中，你觉得 RAG 最难的地方是哪里？", "https://xiaolinnote.com/ai/rag/20_hardest_parts.html"),
    ("RAG", 21, "不同来源的文档发生知识冲突时，RAG 应该信谁？", "https://xiaolinnote.com/ai/rag/21_knowledge_conflict.html"),
    ("工具调用", 1, "什么是 Function Calling？原理是什么？", "https://xiaolinnote.com/ai/tools/1_function_calling.html"),
    ("工具调用", 2, "LLM 是如何学会调用外部工具的？", "https://xiaolinnote.com/ai/tools/2_llm_tool_learning.html"),
    ("工具调用", 3, "大模型的 Function Call 能力是怎么训练出来的？", "https://xiaolinnote.com/ai/tools/3_fc_training.html"),
    ("工具调用", 4, "什么是 MCP（模型上下文协议）？讲讲它的核心内容？", "https://xiaolinnote.com/ai/tools/4_what_is_mcp.html"),
    ("工具调用", 5, "MCP 由哪几部分组成？", "https://xiaolinnote.com/ai/tools/5_mcp_components.html"),
    ("工具调用", 6, "MCP 和 Function Calling 有什么区别？有没有实际跑过 MCP？", "https://xiaolinnote.com/ai/tools/6_mcp_vs_fc.html"),
    ("工具调用", 7, "Function Calling 也属于工具调用，请问什么场景下使用 Function Calling，什么场景下使用 MCP？", "https://xiaolinnote.com/ai/tools/7_fc_vs_mcp_usage.html"),
    ("工具调用", 8, "为什么有些特定的推理模型不支持 MCP 协议？", "https://xiaolinnote.com/ai/tools/8_reasoning_no_mcp.html"),
    ("工具调用", 9, "Skill 是什么？", "https://xiaolinnote.com/ai/tools/9_skill.html"),
    ("工具调用", 10, "MCP 和 Agent Skill 的区别是什么？", "https://xiaolinnote.com/ai/tools/10_mcp_vs_skill.html"),
    ("工具调用", 11, "Function Calling、Skill、MCP 这三个有什么区别？", "https://xiaolinnote.com/ai/tools/11_fc_skill_mcp.html"),
    ("工具调用", 12, "什么是 A2A 协议？它和 MCP 协议的区别是什么？", "https://xiaolinnote.com/ai/tools/12_a2a_protocol.html"),
    ("工具调用", 13, "MCP 协议通常采用什么通信方式？", "https://xiaolinnote.com/ai/tools/13_mcp_transport.html"),
    ("工具调用", 14, "说说 WebSocket 和 SSE 通信的区别及局限性？", "https://xiaolinnote.com/ai/tools/14_sse_vs_websocket.html"),
    ("工具调用", 15, "为什么要用 WebRTC 协议？它和 WebSocket 在 AI 对话流中的核心差异是什么？", "https://xiaolinnote.com/ai/tools/15_webrtc_vs_ws.html"),
    ("工具调用", 16, "有没有用过大模型的网关框架？网关层解决了什么问题？", "https://xiaolinnote.com/ai/tools/16_llm_gateway.html"),
    ("工具调用", 17, "工具很多时，Agent 如何做 Tool Routing，减少 Token 并避免选错工具？", "https://xiaolinnote.com/ai/tools/17_tool_routing.html"),
    ("工具调用", 18, "工具调用格式非法、参数错误、超时或失败时，Agent 如何容错？", "https://xiaolinnote.com/ai/tools/18_tool_reliability.html"),
    ("大模型工程", 1, "什么是大语言模型？和传统 NLP 模型有什么区别？", "https://xiaolinnote.com/ai/llm/what_is_llm.html"),
    ("大模型工程", 2, "讲讲 Transformer 架构基本原理？Encoder 和 Decoder 是什么？", "https://xiaolinnote.com/ai/llm/transformer_architecture.html"),
    ("大模型工程", 3, "多头注意力（MHA）有哪些局限？MQA、GQA、Flash Attention 怎么解决？", "https://xiaolinnote.com/ai/llm/mha_mqa_gqa_flash_attention.html"),
    ("大模型工程", 4, "大模型的位置编码是干什么用的？sin/cos、RoPE、ALiBi 有什么区别？", "https://xiaolinnote.com/ai/llm/position_encoding.html"),
    ("大模型工程", 5, "什么是大模型项目的分词器？原理是什么？", "https://xiaolinnote.com/ai/llm/tokenizer.html"),
    ("大模型工程", 6, "大模型是怎么训练出来的？", "https://xiaolinnote.com/ai/llm/llm_training.html"),
    ("大模型工程", 7, "什么是 Scaling Law？大模型的「涌现能力」是怎么回事？", "https://xiaolinnote.com/ai/llm/scaling_law_emergence.html"),
    ("大模型工程", 8, "大模型微调的方案有哪些？", "https://xiaolinnote.com/ai/llm/finetuning.html"),
    ("大模型工程", 9, "请讲一下 LoRA 技术，除了减少参数量，它还有哪些优点？", "https://xiaolinnote.com/ai/llm/lora.html"),
    ("大模型工程", 10, "SFT 之后还有哪些 Post-Training？RLHF、DPO、GRPO、拒绝采样什么关系？", "https://xiaolinnote.com/ai/llm/post_training.html"),
    ("大模型工程", 11, "大模型的 DPO 和 PPO 的区别是什么？", "https://xiaolinnote.com/ai/llm/dpo_vs_ppo.html"),
    ("大模型工程", 12, "大模型生成文本时的解码策略有哪些？贪心、Beam Search、采样分别什么时候用？", "https://xiaolinnote.com/ai/llm/decoding_strategies.html"),
    ("大模型工程", 13, "大模型的参数：温度值、Top-P、Top-K 分别是什么？各个场景下的最佳设置是什么？", "https://xiaolinnote.com/ai/llm/temperature_top_p_top_k.html"),
    ("大模型工程", 14, "KV Cache 是什么？Prompt Caching 的原理是什么？", "https://xiaolinnote.com/ai/llm/kv_cache_prompt_caching.html"),
    ("大模型工程", 15, "大模型量化是什么？INT8/INT4/AWQ/GPTQ 怎么选？", "https://xiaolinnote.com/ai/llm/quantization.html"),
    ("大模型工程", 16, "如何写好 Prompt？分享下 Prompt 工程实践经验？", "https://xiaolinnote.com/ai/llm/prompt_engineering.html"),
    ("大模型工程", 17, "什么是 CoT？为啥效果好？它有什么缺点或局限性？", "https://xiaolinnote.com/ai/llm/cot.html"),
    ("大模型工程", 18, "大模型为什么会出现幻觉？怎么缓解？", "https://xiaolinnote.com/ai/llm/hallucination.html"),
    ("大模型工程", 19, "MoE 混合专家模型是什么？DeepSeek V3、Qwen 为什么用 MoE？", "https://xiaolinnote.com/ai/llm/moe.html"),
    ("大模型工程", 20, "大模型部署有哪些主流方案？vLLM、TGI、llama.cpp、SGLang 实际项目里怎么选？", "https://xiaolinnote.com/ai/llm/deployment_frameworks.html"),
    ("大模型工程", 21, "大模型能力评测指标有哪些？", "https://xiaolinnote.com/ai/llm/evaluation_metrics.html"),
    ("大模型工程", 22, "对比使用过哪些主流大模型？你们项目中最终选用了哪个模型？为什么？", "https://xiaolinnote.com/ai/llm/model_selection.html"),
    ("大模型工程", 23, "为什么长上下文会出现 Lost in the Middle？上下文窗口越大越好吗？", "https://xiaolinnote.com/ai/llm/23_long_context_lost_middle.html"),
    ("LangChain", 1, "你了解过哪些 AI Agent 开发框架？", "https://xiaolinnote.com/ai/langchain/agent_frameworks.html"),
    ("LangChain", 2, "如何理解 LangChain 中的 Chain？", "https://xiaolinnote.com/ai/langchain/chain.html"),
    ("LangChain", 3, "LangChain 的底层架构与实现原理是什么？", "https://xiaolinnote.com/ai/langchain/langchain_architecture.html"),
    ("LangChain", 4, "使用 LangChain 构建 Agent 的核心步骤是什么？", "https://xiaolinnote.com/ai/langchain/build_agent.html"),
    ("LangChain", 5, "在 LangChain 中，如何为 Agent 注册工具？", "https://xiaolinnote.com/ai/langchain/tool_registration.html"),
    ("LangChain", 6, "LangChain 如何实现短期记忆和长期记忆？", "https://xiaolinnote.com/ai/langchain/memory.html"),
    ("LangChain", 7, "LangChain 和 LlamaIndex 有什么区别？", "https://xiaolinnote.com/ai/langchain/langchain_vs_llamaindex.html"),
    ("LangChain", 8, "请你谈谈 LangChain4j 这类 Java 生态的 LangChain 衍生框架，主要帮开发者解决了哪些核心问题？它的核心适用场景是什么？", "https://xiaolinnote.com/ai/langchain/langchain4j.html"),
    ("LangChain", 9, "请你详细说说 LangChain 和 LangGraph 的核心区别是什么？", "https://xiaolinnote.com/ai/langchain/langchain_vs_langgraph.html"),
    ("LangChain", 10, "LangGraph 相比于 LangChain 有哪些核心优势？更适配哪些 Agent 场景？", "https://xiaolinnote.com/ai/langchain/langgraph_advantages.html"),
    ("LangChain", 11, "LangChain 大版本升级有哪些核心变化？", "https://xiaolinnote.com/ai/langchain/version_evolution.html"),
    ("LangChain", 12, "Deep Research 的实现逻辑和适用场景是什么？", "https://xiaolinnote.com/ai/langchain/deep_research.html"),
]
