"""当前章节与旗舰项目步骤的目录索引。"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CHAPTERS: dict[str, str] = {
    "0.1": "chapters/part0-setup/0.1-environment",
    "0.2": "chapters/part0-setup/0.2-learning-workflow",
    "1.1": "chapters/part1-foundations/1.1-first-call",
    "1.2": "chapters/part1-foundations/1.2-control-output",
    "1.3": "chapters/part1-foundations/1.3-structured-output",
    "1.4": "chapters/part1-foundations/1.4-context-memory",
    "1.5": "chapters/part1-foundations/1.5-tool-calling",
    "1.6": "chapters/part1-foundations/1.6-mcp-intro",
    "1.7": "chapters/part1-foundations/1.7-llm-internals",
    "1.8": "chapters/part1-foundations/1.8-cli-chatbot",
    "2.1": "chapters/part2-rag/2.1-load-split",
    "2.2": "chapters/part2-rag/2.2-embed-retrieve",
    "2.3": "chapters/part2-rag/2.3-minimal-rag",
    "2.4": "chapters/part2-rag/2.4-eval-seed",
    "2.5": "chapters/part2-rag/2.5-raw-sdk-rag-agent-loop",
    "2.6": "chapters/part2-rag/2.6-pdf-sources",
    "2.7": "chapters/part2-rag/2.7-chunk-strategy",
    "2.8": "chapters/part2-rag/2.8-hybrid-search",
    "2.9": "chapters/part2-rag/2.9-query-rewrite",
    "2.10": "chapters/part2-rag/2.10-chroma-persist",
    "2.11": "chapters/part2-rag/2.11-multimodal-rerank",
    "3.1": "chapters/part3-evals/3.1-error-analysis",
    "3.2": "chapters/part3-evals/3.2-eval-basics",
    "3.3": "chapters/part3-evals/3.3-llm-judge",
    "3.4": "chapters/part3-evals/3.4-eval-dataset-build",
    "3.5": "chapters/part3-evals/3.5-eval-dataset-ragas",
    "3.6": "chapters/part3-evals/3.6-langsmith-eval",
    "3.7": "chapters/part3-evals/3.7-eval-regression-curve",
    "3.8": "chapters/part3-evals/3.8-prompt-ab-judge",
    "3.9": "chapters/part3-evals/3.9-agent-trajectory-eval",
    "3.10": "chapters/part3-evals/3.10-eval-report-failures",
    "4.1": "chapters/part4-agents-langgraph/4.1-agent-patterns",
    "4.2": "chapters/part4-agents-langgraph/4.2-langgraph-basics",
    "4.3": "chapters/part4-agents-langgraph/4.3-branch-loop",
    "4.4": "chapters/part4-agents-langgraph/4.4-state-reducer",
    "4.5": "chapters/part4-agents-langgraph/4.5-react-agent",
    "4.6": "chapters/part4-agents-langgraph/4.6-node-reliability",
    "4.7": "chapters/part4-agents-langgraph/4.7-structured-routing",
    "4.8": "chapters/part4-agents-langgraph/4.8-plan-and-execute",
    "4.9": "chapters/part4-agents-langgraph/4.9-observability",
    "4.10": "chapters/part4-agents-langgraph/4.10-checkpoint-context",
    "4.11": "chapters/part4-agents-langgraph/4.11-streaming-hitl",
    "4.12": "chapters/part4-agents-langgraph/4.12-tool-safety-search",
    "4.13": "chapters/part4-agents-langgraph/4.13-text2sql-agent",
    "4.14": "chapters/part4-agents-langgraph/4.14-supervisor-fanout",
    "4.15": "chapters/part4-agents-langgraph/4.15-framework-landscape",
    "5.1": "chapters/part5-production/5.1-serve-fastapi",
    "5.2": "chapters/part5-production/5.2-reliability-retry",
    "5.3": "chapters/part5-production/5.3-cost-cache-routing",
    "5.4": "chapters/part5-production/5.4-sqlite-persistence",
    "5.5": "chapters/part5-production/5.5-docker-packaging",
    "5.6": "chapters/part5-production/5.6-ollama-inference",
    "5.7": "chapters/part5-production/5.7-security-guardrails",
    "5.8": "chapters/part5-production/5.8-pytest-regression",
    "6.1": "chapters/part6-model-tradeoffs/6.1-choose-prompt-rag-finetune",
    "6.2": "chapters/part6-model-tradeoffs/6.2-lora-finetune-optional",
    "8.1": "chapters/part8-ai-quality-optional/8.1-risk-modeling",
    "8.2": "chapters/part8-ai-quality-optional/8.2-eval-data-engineering",
    "8.3": "chapters/part8-ai-quality-optional/8.3-mock-contract-invariant",
    "8.4": "chapters/part8-ai-quality-optional/8.4-rag-layered-testing",
    "8.5": "chapters/part8-ai-quality-optional/8.5-judge-calibration",
    "8.6": "chapters/part8-ai-quality-optional/8.6-agent-trajectory-testing",
    "8.7": "chapters/part8-ai-quality-optional/8.7-api-sse-e2e",
    "8.8": "chapters/part8-ai-quality-optional/8.8-security-resilience-perf",
    "8.9": "chapters/part8-ai-quality-optional/8.9-ci-layered-gate",
    "8.10": "chapters/part8-ai-quality-optional/8.10-production-feedback-loop",
    "9.1": "chapters/part9-enterprise-infra-optional/9.1-intent-fewshot",
    "9.2": "chapters/part9-enterprise-infra-optional/9.2-slot-filling",
    "9.3": "chapters/part9-enterprise-infra-optional/9.3-stable-json-output",
    "9.4": "chapters/part9-enterprise-infra-optional/9.4-intent-workflow",
    "9.5": "chapters/part9-enterprise-infra-optional/9.5-postgres-rls",
    "9.6": "chapters/part9-enterprise-infra-optional/9.6-readonly-sql-explain",
    "9.7": "chapters/part9-enterprise-infra-optional/9.7-redis-cache-ratelimit",
    "9.8": "chapters/part9-enterprise-infra-optional/9.8-vectorstore-selection",
    "9.9": "chapters/part9-enterprise-infra-optional/9.9-compose-linux-ops",
    "9.10": "chapters/part9-enterprise-infra-optional/9.10-openai-compatible-provider",
    "9.11": "chapters/part9-enterprise-infra-optional/9.11-vllm-gpu",
    "9.12": "chapters/part9-enterprise-infra-optional/9.12-inference-benchmark",
    "10.1": "chapters/part10-mcp-a2a-optional/10.1-mcp-auth-approval",
    "10.2": "chapters/part10-mcp-a2a-optional/10.2-a2a-agent-card-task",
    "10.3": "chapters/part10-mcp-a2a-optional/10.3-a2a-protocol-bindings",
    "10.4": "chapters/part10-mcp-a2a-optional/10.4-cross-agent-delegation",
}

FLAGSHIP_STEPS: tuple[str, ...] = (
    "m1-rag-mvp/step1",
    "m1-rag-mvp/step2",
    "m1-rag-mvp/step3",
    "m1-rag-mvp/step4",
    "m2-session-langgraph/step1",
    "m2-session-langgraph/step2",
    "m3-order-tool-reliability/step1",
    "m3-order-tool-reliability/step2",
    "m3-order-tool-reliability/step3",
    "m3-order-tool-reliability/step4",
    "m4-api-identity-security/step1",
    "m4-api-identity-security/step2",
    "m4-api-identity-security/step3",
    "m4-api-identity-security/step4",
    "m5-injection-pii-observability/step1",
    "m5-injection-pii-observability/step2",
    "m5-injection-pii-observability/step3",
    "m5-injection-pii-observability/step4",
    "m6-quality-gate-container/step1",
    "m6-quality-gate-container/step2",
    "m7-capacity-feedback-recovery/step1",
    "m7-capacity-feedback-recovery/step2",
    "m7-capacity-feedback-recovery/step3",
    "m7-capacity-feedback-recovery/step4",
    "m7-capacity-feedback-recovery/step5",
    "m7-capacity-feedback-recovery/step6",
    "m8-evidence-final-frontend/step1",
    "m8-evidence-final-frontend/step2",
    "m8-evidence-final-frontend/step3",
)


def step_label(step: str) -> str:
    milestone, part = step.split("/")
    return f"里程碑 7.{milestone.split('-', 1)[0][1:]} / {part}"
